TARGETS	= basename cat chgrp chmod chown cksum cmp cp dirname du echo false file head id kill link ln locale logname ls mkdir mkfifo nice pwd renice rm rmdir sleep strings test time touch true tty uname uniq unlink wc
PREFIX	= /usr/local
DESTDIR	=
BINDIR	= $(PREFIX)/bin
CC	= cc
CFLAGSF	= -W -Wall -ansi
CFLAGS	= -g
RM	= rm -f
MKDIR	= mkdir -p
INSTALL	= install


all: $(TARGETS)

basename_OBJS = basename.o
basename_CFLAGS = $(CFLAGSF) $(CFLAGS)
basename: $(basename_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o basename $(basename_OBJS)

cat_OBJS = cat.o
cat_CFLAGS = $(CFLAGSF) $(CFLAGS)
cat: $(cat_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o cat $(cat_OBJS)

chgrp_OBJS = chgrp.o
chgrp_CFLAGS = $(CFLAGSF) $(CFLAGS)
chgrp: $(chgrp_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o chgrp $(chgrp_OBJS)

chmod_OBJS = chmod.o
chmod_CFLAGS = $(CFLAGSF) $(CFLAGS)
chmod: $(chmod_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o chmod $(chmod_OBJS)

chown_OBJS = chown.o
chown_CFLAGS = $(CFLAGSF) $(CFLAGS)
chown: $(chown_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o chown $(chown_OBJS)

cksum_OBJS = cksum.o
cksum_CFLAGS = $(CFLAGSF) $(CFLAGS)
cksum: $(cksum_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o cksum $(cksum_OBJS)

cmp_OBJS = cmp.o
cmp_CFLAGS = $(CFLAGSF) $(CFLAGS)
cmp: $(cmp_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o cmp $(cmp_OBJS)

cp_OBJS = cp.o
cp_CFLAGS = $(CFLAGSF) $(CFLAGS)
cp: $(cp_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o cp $(cp_OBJS)

dirname_OBJS = dirname.o
dirname_CFLAGS = $(CFLAGSF) $(CFLAGS)
dirname: $(dirname_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o dirname $(dirname_OBJS)

du_OBJS = du.o
du_CFLAGS = $(CFLAGSF) $(CFLAGS)
du: $(du_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o du $(du_OBJS)

echo_OBJS = echo.o
echo_CFLAGS = $(CFLAGSF) $(CFLAGS)
echo: $(echo_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o echo $(echo_OBJS)

false_OBJS = false.o
false_CFLAGS = $(CFLAGSF) $(CFLAGS)
false: $(false_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o false $(false_OBJS)

file_OBJS = file.o
file_CFLAGS = $(CFLAGSF) $(CFLAGS)
file: $(file_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o file $(file_OBJS)

head_OBJS = head.o
head_CFLAGS = $(CFLAGSF) $(CFLAGS)
head: $(head_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o head $(head_OBJS)

id_OBJS = id.o
id_CFLAGS = $(CFLAGSF) $(CFLAGS)
id: $(id_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o id $(id_OBJS)

kill_OBJS = kill.o
kill_CFLAGS = $(CFLAGSF) $(CFLAGS)
kill: $(kill_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o kill $(kill_OBJS)

link_OBJS = link.o
link_CFLAGS = $(CFLAGSF) $(CFLAGS)
link: $(link_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o link $(link_OBJS)

ln_OBJS = ln.o
ln_CFLAGS = $(CFLAGSF) $(CFLAGS)
ln: $(ln_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o ln $(ln_OBJS)

locale_OBJS = locale.o
locale_CFLAGS = $(CFLAGSF) $(CFLAGS)
locale: $(locale_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o locale $(locale_OBJS)

logname_OBJS = logname.o
logname_CFLAGS = $(CFLAGSF) $(CFLAGS)
logname: $(logname_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o logname $(logname_OBJS)

ls_OBJS = ls.o
ls_CFLAGS = $(CFLAGSF) $(CFLAGS)
ls: $(ls_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o ls $(ls_OBJS)

mkdir_OBJS = mkdir.o
mkdir_CFLAGS = $(CFLAGSF) $(CFLAGS)
mkdir: $(mkdir_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o mkdir $(mkdir_OBJS)

mkfifo_OBJS = mkfifo.o
mkfifo_CFLAGS = $(CFLAGSF) $(CFLAGS)
mkfifo: $(mkfifo_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o mkfifo $(mkfifo_OBJS)

nice_OBJS = nice.o
nice_CFLAGS = $(CFLAGSF) $(CFLAGS)
nice: $(nice_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o nice $(nice_OBJS)

pwd_OBJS = pwd.o
pwd_CFLAGS = $(CFLAGSF) $(CFLAGS)
pwd: $(pwd_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o pwd $(pwd_OBJS)

renice_OBJS = renice.o
renice_CFLAGS = $(CFLAGSF) $(CFLAGS)
renice: $(renice_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o renice $(renice_OBJS)

rm_OBJS = rm.o
rm_CFLAGS = $(CFLAGSF) $(CFLAGS)
rm: $(rm_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o rm $(rm_OBJS)

rmdir_OBJS = rmdir.o
rmdir_CFLAGS = $(CFLAGSF) $(CFLAGS)
rmdir: $(rmdir_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o rmdir $(rmdir_OBJS)

sleep_OBJS = sleep.o
sleep_CFLAGS = $(CFLAGSF) $(CFLAGS)
sleep: $(sleep_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o sleep $(sleep_OBJS)

strings_OBJS = strings.o
strings_CFLAGS = $(CFLAGSF) $(CFLAGS)
strings: $(strings_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o strings $(strings_OBJS)

test_OBJS = test.o
test_CFLAGS = $(CFLAGSF) $(CFLAGS)
test: $(test_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o test $(test_OBJS)

time_OBJS = time.o
time_CFLAGS = $(CFLAGSF) $(CFLAGS)
time: $(time_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o time $(time_OBJS)

touch_OBJS = touch.o
touch_CFLAGS = $(CFLAGSF) $(CFLAGS)
touch: $(touch_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o touch $(touch_OBJS)

true_OBJS = true.o
true_CFLAGS = $(CFLAGSF) $(CFLAGS)
true: $(true_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o true $(true_OBJS)

tty_OBJS = tty.o
tty_CFLAGS = $(CFLAGSF) $(CFLAGS)
tty: $(tty_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o tty $(tty_OBJS)

uname_OBJS = uname.o
uname_CFLAGS = $(CFLAGSF) $(CFLAGS)
uname: $(uname_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o uname $(uname_OBJS)

uniq_OBJS = uniq.o
uniq_CFLAGS = $(CFLAGSF) $(CFLAGS)
uniq: $(uniq_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o uniq $(uniq_OBJS)

unlink_OBJS = unlink.o
unlink_CFLAGS = $(CFLAGSF) $(CFLAGS)
unlink: $(unlink_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o unlink $(unlink_OBJS)

wc_OBJS = wc.o
wc_CFLAGS = $(CFLAGSF) $(CFLAGS)
wc: $(wc_OBJS)
	$(CC) $(LDFLAGSF) $(LDFLAGS) -o wc $(wc_OBJS)

basename.o: basename.c
	$(CC) $(basename_CFLAGS) -c basename.c

cat.o: cat.c
	$(CC) $(cat_CFLAGS) -c cat.c

chgrp.o: chgrp.c
	$(CC) $(chgrp_CFLAGS) -c chgrp.c

chmod.o: chmod.c
	$(CC) $(chmod_CFLAGS) -c chmod.c

chown.o: chown.c
	$(CC) $(chown_CFLAGS) -c chown.c

cksum.o: cksum.c
	$(CC) $(cksum_CFLAGS) -c cksum.c

cmp.o: cmp.c
	$(CC) $(cmp_CFLAGS) -c cmp.c

cp.o: cp.c
	$(CC) $(cp_CFLAGS) -c cp.c

dirname.o: dirname.c
	$(CC) $(dirname_CFLAGS) -c dirname.c

du.o: du.c
	$(CC) $(du_CFLAGS) -c du.c

echo.o: echo.c
	$(CC) $(echo_CFLAGS) -c echo.c

false.o: false.c
	$(CC) $(false_CFLAGS) -c false.c

file.o: file.c
	$(CC) $(file_CFLAGS) -c file.c

head.o: head.c
	$(CC) $(head_CFLAGS) -c head.c

id.o: id.c
	$(CC) $(id_CFLAGS) -c id.c

kill.o: kill.c
	$(CC) $(kill_CFLAGS) -c kill.c

link.o: link.c
	$(CC) $(link_CFLAGS) -c link.c

ln.o: ln.c
	$(CC) $(ln_CFLAGS) -c ln.c

locale.o: locale.c
	$(CC) $(locale_CFLAGS) -c locale.c

logname.o: logname.c
	$(CC) $(logname_CFLAGS) -c logname.c

ls.o: ls.c
	$(CC) $(ls_CFLAGS) -c ls.c

mkdir.o: mkdir.c
	$(CC) $(mkdir_CFLAGS) -c mkdir.c

mkfifo.o: mkfifo.c
	$(CC) $(mkfifo_CFLAGS) -c mkfifo.c

nice.o: nice.c
	$(CC) $(nice_CFLAGS) -c nice.c

pwd.o: pwd.c
	$(CC) $(pwd_CFLAGS) -c pwd.c

renice.o: renice.c
	$(CC) $(renice_CFLAGS) -c renice.c

rm.o: rm.c
	$(CC) $(rm_CFLAGS) -c rm.c

rmdir.o: rmdir.c
	$(CC) $(rmdir_CFLAGS) -c rmdir.c

sleep.o: sleep.c
	$(CC) $(sleep_CFLAGS) -c sleep.c

strings.o: strings.c
	$(CC) $(strings_CFLAGS) -c strings.c

test.o: test.c
	$(CC) $(test_CFLAGS) -c test.c

time.o: time.c
	$(CC) $(time_CFLAGS) -c time.c

touch.o: touch.c
	$(CC) $(touch_CFLAGS) -c touch.c

true.o: true.c
	$(CC) $(true_CFLAGS) -c true.c

tty.o: tty.c
	$(CC) $(tty_CFLAGS) -c tty.c

uname.o: uname.c
	$(CC) $(uname_CFLAGS) -c uname.c

uniq.o: uniq.c
	$(CC) $(uniq_CFLAGS) -c uniq.c

unlink.o: unlink.c
	$(CC) $(unlink_CFLAGS) -c unlink.c

wc.o: wc.c
	$(CC) $(wc_CFLAGS) -c wc.c

clean:
	$(RM) $(basename_OBJS) $(cat_OBJS) $(chgrp_OBJS) $(chmod_OBJS) $(chown_OBJS) $(cksum_OBJS) $(cmp_OBJS) $(cp_OBJS) $(dirname_OBJS) $(du_OBJS) $(echo_OBJS) $(false_OBJS) $(file_OBJS) $(head_OBJS) $(id_OBJS) $(kill_OBJS) $(link_OBJS) $(ln_OBJS) $(locale_OBJS) $(logname_OBJS) $(ls_OBJS) $(mkdir_OBJS) $(mkfifo_OBJS) $(nice_OBJS) $(pwd_OBJS) $(renice_OBJS) $(rm_OBJS) $(rmdir_OBJS) $(sleep_OBJS) $(strings_OBJS) $(test_OBJS) $(time_OBJS) $(touch_OBJS) $(true_OBJS) $(tty_OBJS) $(uname_OBJS) $(uniq_OBJS) $(unlink_OBJS) $(wc_OBJS)

distclean: clean
	$(RM) $(TARGETS)
install: all
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 basename $(DESTDIR)$(BINDIR)/basename
	$(INSTALL) -m 0755 cat $(DESTDIR)$(BINDIR)/cat
	$(INSTALL) -m 0755 chgrp $(DESTDIR)$(BINDIR)/chgrp
	$(INSTALL) -m 0755 chmod $(DESTDIR)$(BINDIR)/chmod
	$(INSTALL) -m 0755 chown $(DESTDIR)$(BINDIR)/chown
	$(INSTALL) -m 0755 cksum $(DESTDIR)$(BINDIR)/cksum
	$(INSTALL) -m 0755 cmp $(DESTDIR)$(BINDIR)/cmp
	$(INSTALL) -m 0755 cp $(DESTDIR)$(BINDIR)/cp
	$(INSTALL) -m 0755 dirname $(DESTDIR)$(BINDIR)/dirname
	$(INSTALL) -m 0755 du $(DESTDIR)$(BINDIR)/du
	$(INSTALL) -m 0755 echo $(DESTDIR)$(BINDIR)/echo
	$(INSTALL) -m 0755 false $(DESTDIR)$(BINDIR)/false
	$(INSTALL) -m 0755 file $(DESTDIR)$(BINDIR)/file
	$(INSTALL) -m 0755 head $(DESTDIR)$(BINDIR)/head
	$(INSTALL) -m 0755 id $(DESTDIR)$(BINDIR)/id
	$(INSTALL) -m 0755 kill $(DESTDIR)$(BINDIR)/kill
	$(INSTALL) -m 0755 link $(DESTDIR)$(BINDIR)/link
	$(INSTALL) -m 0755 ln $(DESTDIR)$(BINDIR)/ln
	$(INSTALL) -m 0755 locale $(DESTDIR)$(BINDIR)/locale
	$(INSTALL) -m 0755 logname $(DESTDIR)$(BINDIR)/logname
	$(INSTALL) -m 0755 ls $(DESTDIR)$(BINDIR)/ls
	$(INSTALL) -m 0755 mkdir $(DESTDIR)$(BINDIR)/mkdir
	$(INSTALL) -m 0755 mkfifo $(DESTDIR)$(BINDIR)/mkfifo
	$(INSTALL) -m 0755 nice $(DESTDIR)$(BINDIR)/nice
	$(INSTALL) -m 0755 pwd $(DESTDIR)$(BINDIR)/pwd
	$(INSTALL) -m 0755 renice $(DESTDIR)$(BINDIR)/renice
	$(INSTALL) -m 0755 rm $(DESTDIR)$(BINDIR)/rm
	$(INSTALL) -m 0755 rmdir $(DESTDIR)$(BINDIR)/rmdir
	$(INSTALL) -m 0755 sleep $(DESTDIR)$(BINDIR)/sleep
	$(INSTALL) -m 0755 strings $(DESTDIR)$(BINDIR)/strings
	$(INSTALL) -m 0755 test $(DESTDIR)$(BINDIR)/test
	$(INSTALL) -m 0755 time $(DESTDIR)$(BINDIR)/time
	$(INSTALL) -m 0755 touch $(DESTDIR)$(BINDIR)/touch
	$(INSTALL) -m 0755 true $(DESTDIR)$(BINDIR)/true
	$(INSTALL) -m 0755 tty $(DESTDIR)$(BINDIR)/tty
	$(INSTALL) -m 0755 uname $(DESTDIR)$(BINDIR)/uname
	$(INSTALL) -m 0755 uniq $(DESTDIR)$(BINDIR)/uniq
	$(INSTALL) -m 0755 unlink $(DESTDIR)$(BINDIR)/unlink
	$(INSTALL) -m 0755 wc $(DESTDIR)$(BINDIR)/wc
