TARGETS	= basename cat chgrp chmod chown cksum cmp cp df dirname du echo false file find head id kill link ln locale logname ls mkdir mkfifo more mv nice pr printf ps pwd renice rm rmdir sleep strings tail test time touch true tty uname uniq unlink wc who
PREFIX	= /usr/local
DESTDIR	=
BINDIR	= $(PREFIX)/bin
CC	= cc
CPPFLAGSF=
CPPFLAGS=
CFLAGSF	= -W
CFLAGS	= -Wall -g -O2 -pedantic
RM	= rm -f
LN	= ln -f
MKDIR	= mkdir -p
INSTALL	= install


all: $(TARGETS)

basename_OBJS = basename.o
basename_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
basename_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

basename: $(basename_OBJS)
	$(CC) -o basename $(basename_OBJS) $(basename_LDFLAGS)

cat_OBJS = cat.o
cat_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
cat_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

cat: $(cat_OBJS)
	$(CC) -o cat $(cat_OBJS) $(cat_LDFLAGS)

chgrp_OBJS = chgrp.o
chgrp_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
chgrp_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

chgrp: $(chgrp_OBJS)
	$(CC) -o chgrp $(chgrp_OBJS) $(chgrp_LDFLAGS)

chmod_OBJS = chmod.o
chmod_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
chmod_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

chmod: $(chmod_OBJS)
	$(CC) -o chmod $(chmod_OBJS) $(chmod_LDFLAGS)

chown_OBJS = chown.o
chown_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
chown_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

chown: $(chown_OBJS)
	$(CC) -o chown $(chown_OBJS) $(chown_LDFLAGS)

cksum_OBJS = cksum.o
cksum_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
cksum_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

cksum: $(cksum_OBJS)
	$(CC) -o cksum $(cksum_OBJS) $(cksum_LDFLAGS)

cmp_OBJS = cmp.o
cmp_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
cmp_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

cmp: $(cmp_OBJS)
	$(CC) -o cmp $(cmp_OBJS) $(cmp_LDFLAGS)

cp_OBJS = cp.o
cp_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
cp_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

cp: $(cp_OBJS)
	$(CC) -o cp $(cp_OBJS) $(cp_LDFLAGS)

df_OBJS = df.o
df_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
df_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

df: $(df_OBJS)
	$(CC) -o df $(df_OBJS) $(df_LDFLAGS)

dirname_OBJS = dirname.o
dirname_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
dirname_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

dirname: $(dirname_OBJS)
	$(CC) -o dirname $(dirname_OBJS) $(dirname_LDFLAGS)

du_OBJS = du.o
du_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
du_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

du: $(du_OBJS)
	$(CC) -o du $(du_OBJS) $(du_LDFLAGS)

echo_OBJS = echo.o
echo_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
echo_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

echo: $(echo_OBJS)
	$(CC) -o echo $(echo_OBJS) $(echo_LDFLAGS)

false_OBJS = false.o
false_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
false_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

false: $(false_OBJS)
	$(CC) -o false $(false_OBJS) $(false_LDFLAGS)

file_OBJS = file.o
file_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
file_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

file: $(file_OBJS)
	$(CC) -o file $(file_OBJS) $(file_LDFLAGS)

find_OBJS = find.o
find_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
find_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

find: $(find_OBJS)
	$(CC) -o find $(find_OBJS) $(find_LDFLAGS)

head_OBJS = head.o
head_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
head_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

head: $(head_OBJS)
	$(CC) -o head $(head_OBJS) $(head_LDFLAGS)

id_OBJS = id.o
id_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
id_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

id: $(id_OBJS)
	$(CC) -o id $(id_OBJS) $(id_LDFLAGS)

kill_OBJS = kill.o
kill_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
kill_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

kill: $(kill_OBJS)
	$(CC) -o kill $(kill_OBJS) $(kill_LDFLAGS)

link_OBJS = link.o
link_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
link_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

link: $(link_OBJS)
	$(CC) -o link $(link_OBJS) $(link_LDFLAGS)

ln_OBJS = ln.o
ln_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
ln_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

ln: $(ln_OBJS)
	$(CC) -o ln $(ln_OBJS) $(ln_LDFLAGS)

locale_OBJS = locale.o
locale_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
locale_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

locale: $(locale_OBJS)
	$(CC) -o locale $(locale_OBJS) $(locale_LDFLAGS)

logname_OBJS = logname.o
logname_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
logname_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

logname: $(logname_OBJS)
	$(CC) -o logname $(logname_OBJS) $(logname_LDFLAGS)

ls_OBJS = ls.o
ls_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
ls_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

ls: $(ls_OBJS)
	$(CC) -o ls $(ls_OBJS) $(ls_LDFLAGS)

mkdir_OBJS = mkdir.o
mkdir_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
mkdir_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

mkdir: $(mkdir_OBJS)
	$(CC) -o mkdir $(mkdir_OBJS) $(mkdir_LDFLAGS)

mkfifo_OBJS = mkfifo.o
mkfifo_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
mkfifo_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

mkfifo: $(mkfifo_OBJS)
	$(CC) -o mkfifo $(mkfifo_OBJS) $(mkfifo_LDFLAGS)

more_OBJS = more.o
more_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
more_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

more: $(more_OBJS)
	$(CC) -o more $(more_OBJS) $(more_LDFLAGS)

mv_OBJS = mv.o
mv_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
mv_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

mv: $(mv_OBJS)
	$(CC) -o mv $(mv_OBJS) $(mv_LDFLAGS)

nice_OBJS = nice.o
nice_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
nice_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

nice: $(nice_OBJS)
	$(CC) -o nice $(nice_OBJS) $(nice_LDFLAGS)

pr_OBJS = pr.o
pr_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
pr_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

pr: $(pr_OBJS)
	$(CC) -o pr $(pr_OBJS) $(pr_LDFLAGS)

printf_OBJS = printf.o
printf_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
printf_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

printf: $(printf_OBJS)
	$(CC) -o printf $(printf_OBJS) $(printf_LDFLAGS)

ps_OBJS = ps.o
ps_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
ps_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

ps: $(ps_OBJS)
	$(CC) -o ps $(ps_OBJS) $(ps_LDFLAGS)

pwd_OBJS = pwd.o
pwd_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
pwd_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

pwd: $(pwd_OBJS)
	$(CC) -o pwd $(pwd_OBJS) $(pwd_LDFLAGS)

renice_OBJS = renice.o
renice_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
renice_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

renice: $(renice_OBJS)
	$(CC) -o renice $(renice_OBJS) $(renice_LDFLAGS)

rm_OBJS = rm.o
rm_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
rm_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

rm: $(rm_OBJS)
	$(CC) -o rm $(rm_OBJS) $(rm_LDFLAGS)

rmdir_OBJS = rmdir.o
rmdir_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
rmdir_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

rmdir: $(rmdir_OBJS)
	$(CC) -o rmdir $(rmdir_OBJS) $(rmdir_LDFLAGS)

sleep_OBJS = sleep.o
sleep_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
sleep_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

sleep: $(sleep_OBJS)
	$(CC) -o sleep $(sleep_OBJS) $(sleep_LDFLAGS)

strings_OBJS = strings.o
strings_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
strings_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

strings: $(strings_OBJS)
	$(CC) -o strings $(strings_OBJS) $(strings_LDFLAGS)

tail_OBJS = tail.o
tail_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
tail_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

tail: $(tail_OBJS)
	$(CC) -o tail $(tail_OBJS) $(tail_LDFLAGS)

test_OBJS = test.o
test_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
test_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

test: $(test_OBJS)
	$(CC) -o test $(test_OBJS) $(test_LDFLAGS)

time_OBJS = time.o
time_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
time_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

time: $(time_OBJS)
	$(CC) -o time $(time_OBJS) $(time_LDFLAGS)

touch_OBJS = touch.o
touch_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
touch_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

touch: $(touch_OBJS)
	$(CC) -o touch $(touch_OBJS) $(touch_LDFLAGS)

true_OBJS = true.o
true_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
true_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

true: $(true_OBJS)
	$(CC) -o true $(true_OBJS) $(true_LDFLAGS)

tty_OBJS = tty.o
tty_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
tty_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

tty: $(tty_OBJS)
	$(CC) -o tty $(tty_OBJS) $(tty_LDFLAGS)

uname_OBJS = uname.o
uname_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
uname_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

uname: $(uname_OBJS)
	$(CC) -o uname $(uname_OBJS) $(uname_LDFLAGS)

uniq_OBJS = uniq.o
uniq_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
uniq_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

uniq: $(uniq_OBJS)
	$(CC) -o uniq $(uniq_OBJS) $(uniq_LDFLAGS)

unlink_OBJS = unlink.o
unlink_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
unlink_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

unlink: $(unlink_OBJS)
	$(CC) -o unlink $(unlink_OBJS) $(unlink_LDFLAGS)

wc_OBJS = wc.o
wc_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
wc_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

wc: $(wc_OBJS)
	$(CC) -o wc $(wc_OBJS) $(wc_LDFLAGS)

who_OBJS = who.o
who_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
who_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

who: $(who_OBJS)
	$(CC) -o who $(who_OBJS) $(who_LDFLAGS)

basename.o: basename.c
	$(CC) $(basename_CFLAGS) -c basename.c

cat.o: cat.c
	$(CC) $(cat_CFLAGS) -c cat.c

chgrp.o: chgrp.c
	$(CC) $(chgrp_CFLAGS) -c chgrp.c

chmod.o: chmod.c common.c
	$(CC) $(chmod_CFLAGS) -c chmod.c

chown.o: chown.c
	$(CC) $(chown_CFLAGS) -c chown.c

cksum.o: cksum.c
	$(CC) $(cksum_CFLAGS) -c cksum.c

cmp.o: cmp.c
	$(CC) $(cmp_CFLAGS) -c cmp.c

cp.o: cp.c
	$(CC) $(cp_CFLAGS) -c cp.c

df.o: df.c
	$(CC) $(df_CFLAGS) -c df.c

dirname.o: dirname.c
	$(CC) $(dirname_CFLAGS) -c dirname.c

du.o: du.c
	$(CC) $(du_CFLAGS) -c du.c

echo.o: echo.c
	$(CC) $(echo_CFLAGS) -c echo.c

false.o: false.c
	$(CC) $(false_CFLAGS) -c false.c

file.o: file.c
	$(CC) $(file_CFLAGS) -c file.c

find.o: find.c
	$(CC) $(find_CFLAGS) -c find.c

head.o: head.c
	$(CC) $(head_CFLAGS) -c head.c

id.o: id.c
	$(CC) $(id_CFLAGS) -c id.c

kill.o: kill.c
	$(CC) $(kill_CFLAGS) -c kill.c

link.o: link.c
	$(CC) $(link_CFLAGS) -c link.c

ln.o: ln.c
	$(CC) $(ln_CFLAGS) -c ln.c

locale.o: locale.c
	$(CC) $(locale_CFLAGS) -c locale.c

logname.o: logname.c
	$(CC) $(logname_CFLAGS) -c logname.c

ls.o: ls.c
	$(CC) $(ls_CFLAGS) -c ls.c

mkdir.o: mkdir.c common.c
	$(CC) $(mkdir_CFLAGS) -c mkdir.c

mkfifo.o: mkfifo.c common.c
	$(CC) $(mkfifo_CFLAGS) -c mkfifo.c

more.o: more.c
	$(CC) $(more_CFLAGS) -c more.c

mv.o: mv.c
	$(CC) $(mv_CFLAGS) -c mv.c

nice.o: nice.c
	$(CC) $(nice_CFLAGS) -c nice.c

pr.o: pr.c
	$(CC) $(pr_CFLAGS) -c pr.c

printf.o: printf.c
	$(CC) $(printf_CFLAGS) -c printf.c

ps.o: ps.c
	$(CC) $(ps_CFLAGS) -c ps.c

pwd.o: pwd.c
	$(CC) $(pwd_CFLAGS) -c pwd.c

renice.o: renice.c
	$(CC) $(renice_CFLAGS) -c renice.c

rm.o: rm.c
	$(CC) $(rm_CFLAGS) -c rm.c

rmdir.o: rmdir.c
	$(CC) $(rmdir_CFLAGS) -c rmdir.c

sleep.o: sleep.c
	$(CC) $(sleep_CFLAGS) -c sleep.c

strings.o: strings.c
	$(CC) $(strings_CFLAGS) -c strings.c

tail.o: tail.c
	$(CC) $(tail_CFLAGS) -c tail.c

test.o: test.c
	$(CC) $(test_CFLAGS) -c test.c

time.o: time.c
	$(CC) $(time_CFLAGS) -c time.c

touch.o: touch.c
	$(CC) $(touch_CFLAGS) -c touch.c

true.o: true.c
	$(CC) $(true_CFLAGS) -c true.c

tty.o: tty.c
	$(CC) $(tty_CFLAGS) -c tty.c

uname.o: uname.c
	$(CC) $(uname_CFLAGS) -c uname.c

uniq.o: uniq.c
	$(CC) $(uniq_CFLAGS) -c uniq.c

unlink.o: unlink.c
	$(CC) $(unlink_CFLAGS) -c unlink.c

wc.o: wc.c
	$(CC) $(wc_CFLAGS) -c wc.c

who.o: who.c
	$(CC) $(who_CFLAGS) -c who.c

clean:
	$(RM) -- $(basename_OBJS) $(cat_OBJS) $(chgrp_OBJS) $(chmod_OBJS) $(chown_OBJS) $(cksum_OBJS) $(cmp_OBJS) $(cp_OBJS) $(df_OBJS) $(dirname_OBJS) $(du_OBJS) $(echo_OBJS) $(false_OBJS) $(file_OBJS) $(find_OBJS) $(head_OBJS) $(id_OBJS) $(kill_OBJS) $(link_OBJS) $(ln_OBJS) $(locale_OBJS) $(logname_OBJS) $(ls_OBJS) $(mkdir_OBJS) $(mkfifo_OBJS) $(more_OBJS) $(mv_OBJS) $(nice_OBJS) $(pr_OBJS) $(printf_OBJS) $(ps_OBJS) $(pwd_OBJS) $(renice_OBJS) $(rm_OBJS) $(rmdir_OBJS) $(sleep_OBJS) $(strings_OBJS) $(tail_OBJS) $(test_OBJS) $(time_OBJS) $(touch_OBJS) $(true_OBJS) $(tty_OBJS) $(uname_OBJS) $(uniq_OBJS) $(unlink_OBJS) $(wc_OBJS) $(who_OBJS)

distclean: clean
	$(RM) -- $(TARGETS)

install: $(TARGETS)
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- basename $(DESTDIR)$(BINDIR)/basename
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- cat $(DESTDIR)$(BINDIR)/cat
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- chgrp $(DESTDIR)$(BINDIR)/chgrp
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- chmod $(DESTDIR)$(BINDIR)/chmod
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- chown $(DESTDIR)$(BINDIR)/chown
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- cksum $(DESTDIR)$(BINDIR)/cksum
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- cmp $(DESTDIR)$(BINDIR)/cmp
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- cp $(DESTDIR)$(BINDIR)/cp
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- df $(DESTDIR)$(BINDIR)/df
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- dirname $(DESTDIR)$(BINDIR)/dirname
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- du $(DESTDIR)$(BINDIR)/du
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- echo $(DESTDIR)$(BINDIR)/echo
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- false $(DESTDIR)$(BINDIR)/false
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- file $(DESTDIR)$(BINDIR)/file
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- find $(DESTDIR)$(BINDIR)/find
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- head $(DESTDIR)$(BINDIR)/head
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- id $(DESTDIR)$(BINDIR)/id
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- kill $(DESTDIR)$(BINDIR)/kill
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- link $(DESTDIR)$(BINDIR)/link
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- ln $(DESTDIR)$(BINDIR)/ln
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- locale $(DESTDIR)$(BINDIR)/locale
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- logname $(DESTDIR)$(BINDIR)/logname
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- ls $(DESTDIR)$(BINDIR)/ls
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- mkdir $(DESTDIR)$(BINDIR)/mkdir
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- mkfifo $(DESTDIR)$(BINDIR)/mkfifo
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- more $(DESTDIR)$(BINDIR)/more
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- mv $(DESTDIR)$(BINDIR)/mv
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- nice $(DESTDIR)$(BINDIR)/nice
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- pr $(DESTDIR)$(BINDIR)/pr
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- printf $(DESTDIR)$(BINDIR)/printf
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- ps $(DESTDIR)$(BINDIR)/ps
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- pwd $(DESTDIR)$(BINDIR)/pwd
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- renice $(DESTDIR)$(BINDIR)/renice
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- rm $(DESTDIR)$(BINDIR)/rm
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- rmdir $(DESTDIR)$(BINDIR)/rmdir
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- sleep $(DESTDIR)$(BINDIR)/sleep
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- strings $(DESTDIR)$(BINDIR)/strings
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- tail $(DESTDIR)$(BINDIR)/tail
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- test $(DESTDIR)$(BINDIR)/test
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- time $(DESTDIR)$(BINDIR)/time
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- touch $(DESTDIR)$(BINDIR)/touch
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- true $(DESTDIR)$(BINDIR)/true
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- tty $(DESTDIR)$(BINDIR)/tty
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- uname $(DESTDIR)$(BINDIR)/uname
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- uniq $(DESTDIR)$(BINDIR)/uniq
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- unlink $(DESTDIR)$(BINDIR)/unlink
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- wc $(DESTDIR)$(BINDIR)/wc
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 -- who $(DESTDIR)$(BINDIR)/who

uninstall:
	$(RM) -- $(DESTDIR)$(BINDIR)/basename
	$(RM) -- $(DESTDIR)$(BINDIR)/cat
	$(RM) -- $(DESTDIR)$(BINDIR)/chgrp
	$(RM) -- $(DESTDIR)$(BINDIR)/chmod
	$(RM) -- $(DESTDIR)$(BINDIR)/chown
	$(RM) -- $(DESTDIR)$(BINDIR)/cksum
	$(RM) -- $(DESTDIR)$(BINDIR)/cmp
	$(RM) -- $(DESTDIR)$(BINDIR)/cp
	$(RM) -- $(DESTDIR)$(BINDIR)/df
	$(RM) -- $(DESTDIR)$(BINDIR)/dirname
	$(RM) -- $(DESTDIR)$(BINDIR)/du
	$(RM) -- $(DESTDIR)$(BINDIR)/echo
	$(RM) -- $(DESTDIR)$(BINDIR)/false
	$(RM) -- $(DESTDIR)$(BINDIR)/file
	$(RM) -- $(DESTDIR)$(BINDIR)/find
	$(RM) -- $(DESTDIR)$(BINDIR)/head
	$(RM) -- $(DESTDIR)$(BINDIR)/id
	$(RM) -- $(DESTDIR)$(BINDIR)/kill
	$(RM) -- $(DESTDIR)$(BINDIR)/link
	$(RM) -- $(DESTDIR)$(BINDIR)/ln
	$(RM) -- $(DESTDIR)$(BINDIR)/locale
	$(RM) -- $(DESTDIR)$(BINDIR)/logname
	$(RM) -- $(DESTDIR)$(BINDIR)/ls
	$(RM) -- $(DESTDIR)$(BINDIR)/mkdir
	$(RM) -- $(DESTDIR)$(BINDIR)/mkfifo
	$(RM) -- $(DESTDIR)$(BINDIR)/more
	$(RM) -- $(DESTDIR)$(BINDIR)/mv
	$(RM) -- $(DESTDIR)$(BINDIR)/nice
	$(RM) -- $(DESTDIR)$(BINDIR)/pr
	$(RM) -- $(DESTDIR)$(BINDIR)/printf
	$(RM) -- $(DESTDIR)$(BINDIR)/ps
	$(RM) -- $(DESTDIR)$(BINDIR)/pwd
	$(RM) -- $(DESTDIR)$(BINDIR)/renice
	$(RM) -- $(DESTDIR)$(BINDIR)/rm
	$(RM) -- $(DESTDIR)$(BINDIR)/rmdir
	$(RM) -- $(DESTDIR)$(BINDIR)/sleep
	$(RM) -- $(DESTDIR)$(BINDIR)/strings
	$(RM) -- $(DESTDIR)$(BINDIR)/tail
	$(RM) -- $(DESTDIR)$(BINDIR)/test
	$(RM) -- $(DESTDIR)$(BINDIR)/time
	$(RM) -- $(DESTDIR)$(BINDIR)/touch
	$(RM) -- $(DESTDIR)$(BINDIR)/true
	$(RM) -- $(DESTDIR)$(BINDIR)/tty
	$(RM) -- $(DESTDIR)$(BINDIR)/uname
	$(RM) -- $(DESTDIR)$(BINDIR)/uniq
	$(RM) -- $(DESTDIR)$(BINDIR)/unlink
	$(RM) -- $(DESTDIR)$(BINDIR)/wc
	$(RM) -- $(DESTDIR)$(BINDIR)/who

.PHONY: all clean distclean install uninstall
