/*
 * This file was generated by the mkbuiltins program.
 */

#include "shell.h"
#include "builtins.h"

int bltincmd();
int breakcmd();
int cdcmd();
int dotcmd();
int echocmd();
int evalcmd();
int execcmd();
int exitcmd();
int exportcmd();
int exprcmd();
int getoptscmd();
int hashcmd();
int jobidcmd();
int jobscmd();
int localcmd();
int pwdcmd();
int readcmd();
int returncmd();
int setcmd();
int setvarcmd();
int shiftcmd();
int trapcmd();
int truecmd();
int umaskcmd();
int unsetcmd();
int waitcmd();

int (*const builtinfunc[])() = {
	bltincmd,
	breakcmd,
	cdcmd,
	dotcmd,
	echocmd,
	evalcmd,
	execcmd,
	exitcmd,
	exportcmd,
	exprcmd,
	getoptscmd,
	hashcmd,
	jobidcmd,
	jobscmd,
	localcmd,
	pwdcmd,
	readcmd,
	returncmd,
	setcmd,
	setvarcmd,
	shiftcmd,
	trapcmd,
	truecmd,
	umaskcmd,
	unsetcmd,
	waitcmd,
};

const struct builtincmd builtincmd[] = {
	"command", 0,
	"break", 1,
	"continue", 1,
	"cd", 2,
	"chdir", 2,
	".", 3,
	"echo", 4,
	"eval", 5,
	"exec", 6,
	"exit", 7,
	"export", 8,
	"readonly", 8,
	"expr", 9,
	"test", 9,
	"[", 9,
	"getopts", 10,
	"hash", 11,
	"jobid", 12,
	"jobs", 13,
	"local", 14,
	"pwd", 15,
	"read", 16,
	"return", 17,
	"set", 18,
	"setvar", 19,
	"shift", 20,
	"trap", 21,
	":", 22,
	"true", 22,
	"false", 22,
	"umask", 23,
	"unset", 24,
	"wait", 25,
	NULL, 0
};
