		<div class="headline" style="float: right; text-align: center">
			<div style="display: table-cell; text-align: left; white-space: nowrap">Page generated by DaPortal<br/>
XHTML 1.1 compliance in mind</div>
			<div style="display: table-cell; width: 15%">&nbsp;</div>
			<div style="display: table-cell; text-align: center; white-space: nowrap"><a href="http://swpat.ffii.org/">No to software patents<br/>
Non aux brevets logiciels</a></div>
			<div style="display: table-cell; width: 15%">&nbsp;</div>
			<div style="display: table-cell; text-align: right; white-space: nowrap"><a href="http://www.vim.org"><img src="images/vim_small.png" alt="VIM"/></a><a href="http://validator.w3.org/check/referer"> <img src="images/valid-xhtml11.png" alt="Valid XHTML 1.1!"/></a></div>
		</div>

		</div>
	</div>
