/* $Id$ */
/* Copyright (c) 2008 Pierre Pronchery <khorben@defora.org> */
/* This file is part of DeforaOS Devel c99 */
/* c99 is not free software; you can redistribute it and/or modify it under the
 * terms of the Creative Commons Attribution-NonCommercial-ShareAlike 3.0
 * Unported as published by the Creative Commons organization.
 *
 * c99 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE.  See the Creative Commons Attribution-NonCommercial-
 * ShareAlike 3.0 Unported license for more details.
 *
 * You should have received a copy of the Creative Commons Attribution-
 * NonCommercial-ShareAlike 3.0 along with c99; if not, browse to
 * http://creativecommons.org/licenses/by-nc-sa/3.0/ */



#include "c99.h"
#include "tokenset.h"


/* protected */
/* variables */
/* declaration */
static TokenCode _c99set_declaration[] =
{
	/* FIXME implement */
	C99_CODE_NULL
};
TokenSet c99set_declaration = _c99set_declaration;


/* keyword */
static TokenCode _c99set_keyword[] =
{
	C99_CODE_KEYWORD_AUTO,
	C99_CODE_KEYWORD_BREAK,
	C99_CODE_KEYWORD_CASE,
	C99_CODE_KEYWORD_CHAR,
	C99_CODE_KEYWORD_CONST,
	C99_CODE_KEYWORD_CONTINUE,
	C99_CODE_KEYWORD_DEFAULT,
	C99_CODE_KEYWORD_DO,
	C99_CODE_KEYWORD_DOUBLE,
	C99_CODE_KEYWORD_ELSE,
	C99_CODE_KEYWORD_ENUM,
	C99_CODE_KEYWORD_EXTERN,
	C99_CODE_KEYWORD_FLOAT,
	C99_CODE_KEYWORD_FOR,
	C99_CODE_KEYWORD_GOTO,
	C99_CODE_KEYWORD_IF,
	C99_CODE_KEYWORD_INLINE,
	C99_CODE_KEYWORD_INT,
	C99_CODE_KEYWORD_LONG,
	C99_CODE_KEYWORD_REGISTER,
	C99_CODE_KEYWORD_RESTRICT,
	C99_CODE_KEYWORD_RETURN,
	C99_CODE_KEYWORD_SHORT,
	C99_CODE_KEYWORD_SIGNED,
	C99_CODE_KEYWORD_SIZEOF,
	C99_CODE_KEYWORD_STATIC,
	C99_CODE_KEYWORD_STRUCT,
	C99_CODE_KEYWORD_SWITCH,
	C99_CODE_KEYWORD_TYPEDEF,
	C99_CODE_KEYWORD_UNION,
	C99_CODE_KEYWORD_UNSIGNED,
	C99_CODE_KEYWORD_VOID,
	C99_CODE_KEYWORD_VOLATILE,
	C99_CODE_KEYWORD_WHILE,
	C99_CODE_KEYWORD__BOOL,
	C99_CODE_KEYWORD__COMPLEX,
	C99_CODE_KEYWORD__IMAGINARY,
	C99_CODE_NULL
};

TokenSet c99set_keyword = _c99set_keyword;


/* punctuator */
static TokenCode _c99set_punctuator[] =
{
	C99_CODE_OPERATOR_LBRACKET,
	C99_CODE_OPERATOR_RBRACKET,
	C99_CODE_OPERATOR_LPAREN,
	C99_CODE_OPERATOR_RPAREN,
	C99_CODE_OPERATOR_LBRACE,
	C99_CODE_OPERATOR_RBRACE,
	C99_CODE_OPERATOR_DOT,
	C99_CODE_OPERATOR_MGREATER,
	C99_CODE_OPERATOR_DPLUS,
	C99_CODE_OPERATOR_DMINUS,
	C99_CODE_OPERATOR_AMPERSAND,
	C99_CODE_OPERATOR_TIMES,
	C99_CODE_OPERATOR_PLUS,
	C99_CODE_OPERATOR_MINUS,
	C99_CODE_OPERATOR_TILDE,
	C99_CODE_OPERATOR_NOT,
	C99_CODE_OPERATOR_DIVIDE,
	C99_CODE_OPERATOR_MODULO,
	C99_CODE_OPERATOR_DLESS,
	C99_CODE_OPERATOR_DGREATER,
	C99_CODE_OPERATOR_LESS,
	C99_CODE_OPERATOR_GREATER,
	C99_CODE_OPERATOR_LEQUALS,
	C99_CODE_OPERATOR_GEQUALS,
	C99_CODE_OPERATOR_DEQUALS,
	C99_CODE_OPERATOR_NEQUALS,
	C99_CODE_OPERATOR_XOR,
	C99_CODE_OPERATOR_BAR,
	C99_CODE_OPERATOR_DAMPERSAND,
	C99_CODE_OPERATOR_DBAR,
	C99_CODE_OPERATOR_QUESTION,
	C99_CODE_OPERATOR_COLON,
	C99_CODE_OPERATOR_SEMICOLON,
	C99_CODE_OPERATOR_DOTDOTDOT,
	C99_CODE_OPERATOR_EQUALS,
	C99_CODE_OPERATOR_TEQUALS,
	C99_CODE_OPERATOR_DEQUALS, /* FIXME "/=" ambiguity with "==" */
	C99_CODE_OPERATOR_MODEQUALS,
	C99_CODE_OPERATOR_PEQUALS,
	C99_CODE_OPERATOR_MEQUALS,
	C99_CODE_OPERATOR_DLEQUALS,
	C99_CODE_OPERATOR_DGEQUALS,
	C99_CODE_OPERATOR_AEQUALS,
	C99_CODE_OPERATOR_XEQUALS,
	C99_CODE_OPERATOR_BEQUALS,
	C99_CODE_COMMA,
	C99_CODE_OPERATOR_HASH,
	C99_CODE_OPERATOR_DHASH,
	C99_CODE_NULL
};

TokenSet c99set_punctuator = _c99set_punctuator;


/* storage class specifier */
static TokenCode _c99set_storage_class_specifier[] =
{
	C99_CODE_KEYWORD_TYPEDEF,
	C99_CODE_KEYWORD_EXTERN,
	C99_CODE_KEYWORD_STATIC,
	C99_CODE_KEYWORD_AUTO,
	C99_CODE_KEYWORD_REGISTER,
	C99_CODE_NULL
};

TokenSet c99set_storage_class_specifier = _c99set_storage_class_specifier;


/* type qualifier */
static TokenCode _c99set_type_qualifier[] =
{
	C99_CODE_KEYWORD_CONST,
	C99_CODE_KEYWORD_RESTRICT,
	C99_CODE_KEYWORD_VOLATILE,
	C99_CODE_NULL
};

TokenSet c99set_type_qualifier = _c99set_type_qualifier;


/* type specifier */
static TokenCode _c99set_type_specifier[] =
{
	C99_CODE_KEYWORD_VOID,
	C99_CODE_KEYWORD_CHAR,
	C99_CODE_KEYWORD_SHORT,
	C99_CODE_KEYWORD_INT,
	C99_CODE_KEYWORD_LONG,
	C99_CODE_KEYWORD_FLOAT,
	C99_CODE_KEYWORD_DOUBLE,
	C99_CODE_KEYWORD_SIGNED,
	C99_CODE_KEYWORD_UNSIGNED,
	C99_CODE_KEYWORD__BOOL,
	C99_CODE_KEYWORD__COMPLEX,
	C99_CODE_KEYWORD__IMAGINARY,
	C99_CODE_KEYWORD_STRUCT,
	C99_CODE_KEYWORD_UNION,
	C99_CODE_KEYWORD_ENUM,
	C99_CODE_KEYWORD_TYPEDEF,
	C99_CODE_NULL
};

TokenSet c99set_type_specifier = _c99set_type_specifier;
