#! /bin/sh
# $Id$
# Copyright (c) 2009 Pierre Pronchery <khorben@defora.org>
# This file is part of DeforaOS Unix scripts
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, version 3 of the License.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.



# usage
if [ $# -eq 0 -o "$1" = "-h" -o $# -eq 1 -a "$1" = "--" ]; then
	echo "Usage: watch command..." 2>&1
	exit 1
fi
[ "$1" = "--" ] && shift 1


# main
while true; do
	clear
	date
	echo
	"$@"
	sleep 2
done
