#! /bin/sh
# $Id$
# Copyright (c) 2007 Pierre Pronchery <khorben@defora.org> */
# This file is part of DeforaOS Unix scripts */
# scripts is not free software; you can redistribute it and/or modify it under
# the terms of the Creative Commons Attribution-NonCommercial-ShareAlike 3.0
# Unported as published by the Creative Commons organization.
#
# scripts is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the Creative Commons Attribution-NonCommercial-
# ShareAlike 3.0 Unported license for more details.
#
# You should have received a copy of the Creative Commons Attribution-
# NonCommercial-ShareAlike 3.0 along with scripts; if not, browse to
# http://creativecommons.org/licenses/by-nc-sa/3.0/



# usage
if [ $# -ne 1 -o "$1" = "-h" ]; then
	echo "Usage: which command" 2>&1
	exit 1
fi


# main
P="$PATH"
while [ -n "$P" ]; do
	CUR=`echo "$P" | cut -d ':' -f 1`
	if [ -x "$CUR/$1" ]; then
		echo "$1 is $CUR/$1"
		exit 0
	fi
	P=`echo "$P" | cut -d ':' -f 2-`
	[ "$CUR" = "$P" ] && break
done
exit 2
