#! /bin/sh
# $Id$
# Copyright (c) 2009 Pierre Pronchery <khorben@defora.org>
# This file is part of DeforaOS Unix scripts
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, version 3 of the License.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.



# usage
if [ $# -ne 1 -o "$1" = "-h" ]; then
	echo "Usage: which command" 2>&1
	exit 1
fi


# main
P="$PATH"
while [ -n "$P" ]; do
	CUR=`echo "$P" | cut -d ':' -f 1`
	if [ -x "$CUR/$1" ]; then
		echo "$1 is $CUR/$1"
		exit 0
	fi
	P=`echo "$P" | cut -d ':' -f 2-`
	[ "$CUR" = "$P" ] && break
done
exit 2
