#!/bin/sh


RESOLVCONF="/sbin/resolvconf"

if [ $# -ne 5 -a $# -ne 6 ]; then
	echo "Usage: ip-up interface tty speed local remote [parameter]" 1>&2
	exit 1
fi
interface="$1"

[ "$USEPEERDNS" -eq 1 ] && $RESOLVCONF -a "$interface" < "/etc/ppp/resolv.conf"
